### ISSUE TITLE
add filtering for location on server

### ISSUE THREAD

**Issue by lmccart** [lmccart/pplkpr-node-server#5]

**Comment by kylemcdonald** [comment]
each report is given an attribute of `inside` which is true or false. this isn't used for filtering the data, because ultimately only people who are added to the `people` database will show up on the screens because of this line https://github.com/lmccart/pplkpr-node-server/commit/2681f6f8f0e59793776cfb54e24b281ed786f4f0#diff-78c12f5adc1848d13b1c6f07055d996eR236

if someone were to submit a report from nyc about someone attending NODE, it would be used for scoring.
